biddr_api/config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
resources :auctions do
  resources :bids, only: [:create]
end
resource :session, only:[:new, :create, :destroy]
root "auctions#index"
  

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :auctions do
        resources :bids, only: [:create]

      end
      
      resource :session, only: [:create, :destroy]
      resource :users, only: [:create] do
        get :current, on: :collection
      end
      resources :bids, only: [:create]
    end
  end
end

biddr_api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

biddr_api/app/models/auction.rb
class Auction < ApplicationRecord

    has_many :bids, dependent: :destroy
    belongs_to :user
    validates :title, presence: {message: "Must input Title"}
    validates :description, presence: {message: "Must input description"}
    validates :price, numericality: {greater_than_or_equal_to: 0}
end

biddr_api/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :user
end

biddr_api/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :bids
    has_many :auctions
    
    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX

    def full_name
        self.first_name + " " + self.last_name
    end
end

biddr_api/app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
    skip_before_action :verify_authenticity_token
    
    private
    def authenticate_user!
        redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
        # render json: "Need to sign in with session"
    end
end

biddr_api/app/controllers/api/v1/auctions_controller.rb
class Api::V1::AuctionsController < Api::ApplicationController
    before_action :authenticate_user!, except: [:index, :show]    
    
    def index
        auctions = Auction.order(created_at: :desc)
        render(json: auctions)
        # each_serializer: AuctionCollectionSerializer
     
    end

    def show
        auction = Auction.find(params[:id])
        render(json: auction)
        
    end

    def create
        auction = Auction.new(auction_params)
        auction.user = current_user
        if auction.save
            render json: {id: auction.id}
        else
            render(
                json: {errors: auction.errors.messages },
                status: 422 
            )
        end
        
    end




    private 
    def auction_params
        params.require(:auction).permit(:title, :description, :price, :end_date)
    end
end

biddr_api/app/controllers/api/v1/bids_controller.rb
class Api::V1::BidsController < Api::ApplicationController
    before_action :authenticate_user!, except: [:create]
    def create
        auction = Auction.find(params[:auction_id])
        bid = Bid.new(bid_params)
        bid.auction = auction
        bid.user = current_user
        if bid.save
            render json: {id: bid.id}
        else
            render(
                json: {errors: bid.errors.messages },
                status: 422 
            )
        end
    end

  

    private 
    def bid_params
        params.require(:bid).permit(:price)
    end
end

biddr_api/app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::ApplicationController
    def create
        user = User.find_by(email: params[:email])

        if user&.authenticate(params[:password])
            session[:user_id] = user.id
            render json: { id: user.id }
        else
            render(
                json: { status: 404 },
                status: 404
            )
        end
    end

    
    def destroy
        session[:user_id] = nil
        render json: {id:nil}
        
    end
end

biddr_api/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::ApplicationController
    def current
        render json: current_user
         
     end
 
     def create
         user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
 
         user = User.new user_params
         if user.save
             session[:user_id] = user.id
             render json: {id: user.id}
         else
             render(
                 json: {error: user.errors.messages},
                 status: 422 #unprocessable entity
             )
 
         end
     end
end

biddr_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    

    def current_user
        @current_user ||= User.find_by_id session[:user_id]
        
    end

    helper_method :current_user
    #helper_method makes the method also available for the views

    def user_signed_in?
        current_user.present?

    end

    helper_method :user_signed_in?

    def authenticate_user!
        redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
        
    end

end

biddr_api/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
    before_action :find_auction, only: [:edit, :update, :show, :destroy]
 def new   
    @auction = Auction.new
end

def create
   
    @auction = Auction.new(auction_params)
    @auction.user = current_user
    if @auction.save
         
        #ProductMailer.new_product(@auction).deliver_now

        flash[:success] = "Question successfully created"
         redirect_to @auction
                #same thing as = product_path(@auction.id), but just shorter
    else
        flash[:error] = "Something went wrong"
        render 'new', status: 303
            #same as :new, firing new method
     end
end

def index
    @auctions = Auction.order(created_at: :desc)
end

def show
    @bids = @auction.bids.order(created_at: :desc)
    @bid = Bid.new
    # @reviews = @product.reviews.order(created_at: :desc)
end


private
def find_auction
    @auction = Auction.find params[:id]
end

    def auction_params
        params.require(:auction).permit(:title, :description, :price, :end_date)
    end
end

biddr_api/app/controllers/bids_controller.rb
class BidsController < ApplicationController
    before_action :find_auction

    def create
        @bid = Bid.new(bid_params)
        @bid.auction = @auction
        @bid.user = current_user 
        if @bid.save
            redirect_to @auction
        end
    end

    private
    def find_auction
        @auction = Auction.find params[:auction_id]
      end

      def bid_params
        params.require(:bid).permit(:price)
     end
end

biddr_api/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    #authenticate needs an argument, which is the password that you need to check
    
    if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path, {notice: "Logged in"}
    else
      render :new, {alert: "Wrong Email or password", status: 303}
    end

  end

  def destroy
    session[:user_id] = nil
    flash.notice = "Logged out"
    redirect_to root_path
  end
end

biddr_api/app/helpers/application_helper.rb
module ApplicationHelper
end

biddr_api/app/helpers/auctions_helper.rb
module AuctionsHelper
end

biddr_api/app/helpers/bids_helper.rb
module BidsHelper
end

biddr_api/app/helpers/sessions_helper.rb
module SessionsHelper
end

biddr_api/app/views/auctions/index.html.erb
<%@auctions.each do |auction|%>
  <h2> <%= link_to auction.title, auction%>
  <% end %>

biddr_api/app/views/auctions/new.html.erb
<h2>Create New Auction</h2>
<%= form_with(model: @auction) do |form|%>
  <div>
    <%= form.label :title%>
    <br>
    <%= form.text_field :title%>
  </div>
  <div>
    <%= form.label :description%>
    <br>
    <%= form.text_area :description%>
  </div>
  <div>
    <%= form.label :price%>
    <br>
    <%= form.number_field :price, step: "0.01"%>
  </div>
  <div>
    <%= form.label :end_date%>
    <br>
    <%= form.date_field :end_date%>
  </div>
  <%= form.submit%>
<% end %>

biddr_api/app/views/auctions/show.html.erb
<h2><%= @auction.title%> </h2>
<p>Author: <%=@auction.user.full_name%></p>
<%= button_to 'Delete', auction_path(@auction), method: :delete, form: {data: {turbo_confirm: "Are you sure?"}} %>
<br>
<hr>
<% @bids.each do |bid|%>
  <p><%= bid.price%> <%=bid.created_at%> <%= bid.user.full_name%> </p>
<% end %>
<%= form_with(model:[@auction, @bid]) do |f| %>
  <div>
    <%= f.label :price %>
    <br>
    <%= f.number_field :price %>
  </div>
  <%= f.submit "Bid" %>
<% end %>

biddr_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiddrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav>
      <%= link_to "Questions Index Page", auctions_path %>
      <%= link_to 'New Question Page', new_auction_path %>
      <% if user_signed_in?%>
        <h5> Hello <%= current_user.full_name%> </h5>
        <%= button_to "Log out", session_path, method: :delete%>
      <% else%>
        <%= link_to 'Sign in', new_session_path %>
        <%#= link_to 'Sign up', new_user_path %>
      <%end%>
    </nav>
    <%= yield %>
  </body>
</html>